package com.DarwinsNatura.common.world.biomes.Galapagos;

import java.util.Random;

import com.DarwinsNatura.common.world.gen.layers.IWeightProvider;

import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.minecraft.world.biome.Biome;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

public class BiomeBaseGalapagos extends Biome {

	public static short biomeWeight;
	public int grassColor, foliageColor;

	public byte topBlockMeta;
	public byte fillerBlockMeta;

	public BiomeBaseGalapagos(BiomeProperties properties) {
		super(properties);
		topBlockMeta = 0;
		fillerBlockMeta = 0;
	}
	
	@Override
    public boolean canRain() {
        return true;
    }
	
	// Every time a biome is generated, this method is called to specify sub biome to generate inside the biome.
	
	//  @param randomValue
	//  value between 0 and 100 (both inclusive) generated by GenLayer
	//  @return sub biome to generate, or null

}
