name: Java CI

on: [push]

jobs:
   build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8 plus gradle
      uses: actions/setup-java@v1 && sudo apt-get update && sudo apt-get install --yes gradle
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: sudo gradlew assemble testClasses
